language: python

script:
  - sh build.sh

deploy:
  provider: releases
  api_key:
    secure: 94a48748c192af0f663dac46cc41491c0bd137c4
  file: python-2.7-ucs4.zip
  skip_cleanup: true
  on:
    tags: true
