language: generic
script:
  - echo "leanken"

before_deploy:
  - sh build.sh

deploy:
  provider: releases
  api_key:
    secure: FyEIRJmLMaR0CQwOCGCfurMryboHE1GBcd66ibkR1qT0we7o9eGtqtdJnuc9qbu6cHbm2WutEwRZ6e57iaCbGl8Yqvx+ZRB+Te/B5mG1HWWIArwMULwt6/ZJHij3q9A2ztrxG9x3v+bs+fZ6DW75+lp8JREzOx+51ua/uCaMqRSxS+g2YO59iWVBwr2GK1jFjqTW1sIATbDEl5K7GflusJzGM6B7x/H9D5n0MKSr0+FuiHhD3KhQWEqbzXHp03az5OoqZ4fdWpOpiM5V8gex7eas4CUGb3iVALQp97LQAnzVv2Dh7GYO4iaYpQsZBpfhdNvLVdCqcHgtZASkgmJ+kZYvT0nAVnBfQW+3H2mUxBo/RJ7zTkc6irjcRuzvVGqnHrk9hc73jJhA8RINYFhyjM8IjHz6wqbAG1BNWzRR6GkoLBZ2pwSVuk0q9atvKqKOUObLRXhQY8eif1WxHpH/Nb5Hf0nIoc5P3edUi/DImsUishNiXjXj6YLOEC4VtPS3LBHO6MDde8z9clwczG1a5cyM0YfCyW/KBFT6B1bqTodtq5Rbu2e8ZMLamJdQAKEiteDwFf/hsTNx1yRsWRk4Po69/Wo8W60buzx/xIqjbJCCK0H4DfSBG9gHYBHX469P9rC/i6390xEr8SdYM15Bt1qGkPq21SRm04oqzr3QOlA=
  file: python-2.7-ucs4.zip
  skip_cleanup: true
  on:
    tags: true
